### ISSUE TITLE
Does not support latest ggml version

### ISSUE THREAD

**Issue by MarkSchmidty** [ItsPi3141/alpaca-electron#11]
Latest ggml conversion of alpaca native does not work with alpaca electron.

I haven't looked deeply, but if this project is based on alpaca.cpp you might consider changing its base to llama.cpp since llama.cpp pulled in the additional functionality of alpaca.cpp making alpaca.cpp redundant and outdated. See here: https://github.com/ggerganov/llama.cpp#instruction-mode-with-alpaca

**Comment by ItsPi3141** [comment]
I'm planning on doing that. I just need to remake the alpaca models first.
