### ISSUE TITLE
Docker failing: failed to compute cache key: "/tmp/alpaca-electron/release-builds/alpaca-electron-linux-x64"

### ISSUE THREAD

**Issue by SympleScience** [ItsPi3141/alpaca-electron#12]
=> ERROR [stage-2 4/8] COPY --chown=1000 --from=alpaca-electron-builder /tmp/alpaca-electron/release-builds/alpa  0.0s
------
 > [stage-2 4/8] COPY --chown=1000 --from=alpaca-electron-builder /tmp/alpaca-electron/release-builds/alpaca-electron-linux-x64 /alpaca-electron:
------
failed to solve: failed to compute cache key: "/tmp/alpaca-electron/release-builds/alpaca-electron-linux-x64" not found: not found

**Comment by ItsPi3141** [comment]
Docker is currently a WIP

**Comment by ItsPi3141** [comment]
Fixed in https://github.com/ItsPi3141/alpaca-electron/commit/553174d8cb41f566238a4034c7f1bd29fff9e8d8
