### ISSUE TITLE
Doesn't remember previous questions

### ISSUE THREAD

**Issue by tjohnman** [ItsPi3141/alpaca-electron#13]
I know this is a limitation of the way alpaca.cpp/llama.cpp interfaces with the Alpaca model, but you can't refer to a previous response in your prompt. For example, if you ask it to explain the JavaScript Fetch API, and then you say "Write a snippet showcasing its usage.", it won't know you're talking about the Fetch API and might write Python code, instead. Right now interaction seems to be limited to standalone prompts.

You can tell it to remember past instructions and it more or less will do so, but it's still very hit and miss. Sometimes referring to previous output will work and other times it will hallucinate an entirely different context in which a conversation was taking place.

For Alpaca, this might be fixed by feeding it the entire chat history every time and telling it to "write the next response", but this has its own issues. Or perhaps only using "### Instruction" and "### Response" for the first prompt. However, doing so degrades the quality of the responses a lot.

**Comment by ItsPi3141** [comment]
I'm working on switching to llama.cpp right now because it has reverse prompting
