### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by BadisG** [ItsPi3141/alpaca-electron#14]
Will the future updates (commits) on llama.cpp be automatically integrated into your frontend? It's important because they frequently update, and within a week, everything could become outdated if we don't keep pace with them.

**Comment by ItsPi3141** [comment]
They will not be automatically updated because they have to be prebuilt. I might work on a system that downloads the executable from GitHub. But that is a trojan-like behavior so it might trigger a lot of anti-viruses. 

For now, I will update them to work with the latest llama.cpp periodically. Right now I'm working on making Alpaca 7B through 30B work with the new q4_1 quantization method in llama.cpp. once that's done, I will update the prebuilt llama.cpp binaries.

**Comment by nigelp** [comment]
So will the new llama.cpp perform faster than the alpaca.cpp version? I'm running your alpaca version (1.4?) and it runs great, but just a little slow on my machine.

**Comment by ItsPi3141** [comment]
> So will the new llama.cpp perform faster than the alpaca.cpp version? 

Actually, no. From my initial testing, reverse prompting makes it slower. And the model is also larger. I might make a setting to switch between the old alpaca.cpp and the new llama.cpp.

**Comment by nigelp** [comment]
That's a very cool idea. I also like your suggestion that people can try different models. This mirrors the Stable Diffusion experience, where people are downloading all sorts of different models from Huggingface aren't they? Eventually a short section on different/recommended models to play with for speed, accuracy etc might be a cool addition to the documentation?

**Comment by ItsPi3141** [comment]
Yes, I guess you could say that. Eventually, people will make their own finetuned models and it will be similar to SD.

**Comment by ItsPi3141** [comment]
Ah, running it on mobile will really slow, sadly. One day we'll get there.

**Comment by ItsPi3141** [comment]
> What about including the llama.cpp repository as a submodule of this one and having the build system just build llama.cpp?

I'll be honest, I got kinda lazy when trying to do that so I just decided to bundle llama.cpp prebuilt. It also is faster than running make/cmake on first run. But I might do that.

**Comment by ItsPi3141** [comment]
Llama.cpp will not automatically update. However, I will try to use the latest llama.cpp when building releases.
