### ISSUE TITLE
Works extremely slowly

### ISSUE THREAD

**Issue by PierrotLaLune** [ItsPi3141/alpaca-electron#15]
I run Windows 10 with an i5, 16 GB Ram and an SSD. 

I get one word every couple seconds to the question "Can you explain quantum computing in simple terms?"
CPU is at 100%, 98.4% from alpaca-electron.

[Doc1.pdf](https://github.com/ItsPi3141/alpaca-electron/files/11105897/Doc1.pdf)

**Comment by ItsPi3141** [comment]
Oh I recently made a change to make it use all threads. It's affecting the performance so I'll revert it in the next update.

**Comment by twerpyfie** [comment]
It would be nice if you could provie an option, where the user can set the threads and other options :)

**Comment by ItsPi3141** [comment]
> It would be nice if you could provie an option, where the user can set the threads and other options :) (Like the temp for example, because different models need different temp)

Yes I'm working on a settings page
