### ISSUE TITLE
Not working on Debian 11

### ISSUE THREAD

**Issue by Senior-S** [ItsPi3141/alpaca-electron#22]
**Describe the bug**
When running the latest version of the model (v1.0.5) on debian, it throws a non descriptive error.

**To Reproduce**
1. Download the version 1.0.5 on Debian 11.
2. Extract the folder and execute `./Alpaca\ Electron`

**Expected behavior**
The app to install or ask me for the path of the model that I want to use.

**Screenshots**
![image](https://user-images.githubusercontent.com/57560155/230796235-ba4aee96-3d1e-4958-a6b4-30f15ff21a5c.png)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Kernel: Linux 5.10.0-21-amd64
 - Architecture: x86-64

**Comment by ItsPi3141** [comment]
This might help
https://github.com/electron/electron/issues/24211

I don't use debian myself so I'm not quite sure.

**Comment by Senior-S** [comment]
I just reinstalled the whole OS and now seems to be working, maybe I mess some files with some tests before installing this app.
Anyways thanks for the help.
