### ISSUE TITLE
does it have AVX support (no AVX2) for Linux? Or only Windows?

### ISSUE THREAD

**Issue by Gituseron** [ItsPi3141/alpaca-electron#23]
Sorry for stupid question if it is so. I ask, as the information about AVX2 mentioned only in Windows topic. Also I tried to run the app on Linux (Ubuntu based) and I am not sure if it worked at all. Because I have chosen the model, the GUI is quite good, but the monitor for CPU and RAM usage where just as always (no rising or something else, about 2GB of RAM for system and 20-40% from CPU). Thank you for understanding, answering and especially your diffucult and awesome work!

**Comment by ItsPi3141** [comment]
Does your CPU support avx2? I haven't tested Linux a lot so I don't know if there needs to be different versions for AVX and AVX2. 

Also make sure your model is stored on an SSD. It takes a long time to load if it's on an HDD.

**Comment by Flizyx** [comment]
theres some tutorials to enable avx on linux, check first with hwinfo

**Comment by fancellu** [comment]
Doesn't work for me on an i7-3820, which doesn't have AVX2, only AVX

**Comment by ItsPi3141** [comment]
> Doesn't work for me on an i7-3820, which doesn't have AVX2, only AVX

It works. I tested it on an i7 2nd gen (I forgot the exact model). Its just really slow if the CPU doesn't support AVX2. From my testing, it took about 30 minutes to generate a paragraph.

**Comment by fancellu** [comment]
Well, not for me, v much goes bang. As do many other chat.exe type things. I had to hand build chat.exe with alpaca previously to make it work.Anyway, I'll be getting a7950X3d system soon. It gets about 30% more performance on DJL taskshttps://djl.ai/As well as that, it sips power compared to 7950X11.04.2023, 21:48, "Pi" ***@***.***>:

Doesn't work for me on an i7-3820, which doesn't have AVX2, only AVX

It works. I tested it on an i7 2nd gen (I forgot the exact model). Its just really slow if the CPU doesn't support AVX2. From my testing, it took about 30 minutes to generate a paragraph.

**Comment by ItsPi3141** [comment]
Just added AVX binary for Linux. It will be fixed in the next update (1.0.6). 
See commit c9b7a80

**Comment by fancellu** [comment]
And windows too?

**Comment by fancellu** [comment]
> > And windows too?
> 
> Windows already has it

Odd, doesn't work for me on my i7-3820

**Comment by ItsPi3141** [comment]
> Odd, doesn't work for me on my i7-3820

I have an i7 3rd gen too. And it works when I test it. Its probably really slow because of two reasons: 

1. If the model is on an HDD, then it takes a long time for it to load.

2. AVX is just really slow.

**Comment by fancellu** [comment]
Chat.exe crashes for me

![image](https://user-images.githubusercontent.com/4273247/236853480-5016654f-88e9-437f-afe5-8e354c84d2bb.png)

Unhandled exception at 0x00007FF65423BFD2 in chat.exe: 0xC000001D: Illegal Instruction.

It it trying to run 

C:\Users\Dino\AppData\Local\Programs\alpaca-electron\resources\app\bin\chat.exe

and not

C:\Users\Dino\AppData\Local\Programs\alpaca-electron\resources\app\bin\no_avx2\chat.exe

In fact if I copy the  no_avx2 version over, it works fine. Slow, but works.
