### ISSUE TITLE
Doesn’t accept path

### ISSUE THREAD

**Issue by iHaagcom** [ItsPi3141/alpaca-electron#3]
I’m providing these models https://rentry.org/nur779 and it keeps asking for a valid model.

**Comment by ItsPi3141** [comment]
Did you link to the file? Or just the folder it was in?

**Comment by iHaagcom** [comment]
Both

**Comment by ItsPi3141** [comment]
Can you try using the file picker?

**Comment by iHaagcom** [comment]
The prompt that asks when it starts up, sometimes it works other times it doesnt, when it works sometimes it doesnt even reply to my prompts

**Comment by ItsPi3141** [comment]
What operating system? On MacOS, you have to allow it to access the folder your file is in.

**Comment by iHaagcom** [comment]
Windows, after a couple of tries it kind of works.

**Comment by ItsPi3141** [comment]
Awesome!
