### ISSUE TITLE
Can't install on Mac OS

### ISSUE THREAD

**Issue by kevinhower** [ItsPi3141/alpaca-electron#30]
**Describe the bug**
Downloaded the version that says it for ARM ... and no joy. I says it is damaged and should be trashed. Does not even give me an option to install.

**To Reproduce**
1.  download
2. drag to applications
3. try to open. It FAILS.

**Expected behavior**
working, as it NOT right now

**Screenshots**
![Screen Shot 2023-04-10 at 3 30 42 PM](https://user-images.githubusercontent.com/7663566/230992774-534c087d-ab28-44b7-8859-d5dc2a24c127.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 12.6
 - Firefox  111.01

**Comment by ItsPi3141** [comment]
Can you try following the instructions for Mac here in the FAQ section
https://github.com/ItsPi3141/alpaca-electron#macos

**Comment by kevinhower** [comment]
I will try that and let you know

**Comment by kevinhower** [comment]
It did not work :( ... I tried that and it didn't even give the options mentioned in that link. It persisted in saying that the app was literally damaged and COULD NOT be opened.

**Comment by Rup1** [comment]
Same issue on M1 Max 64gb. macos Ventura 13.1

**Comment by dvoidus** [comment]
I tried the latest release Alpaca-Electron-mac-arm64-v1.0.5 but it gives me the same error message.
MacOS: 13.2.1
Macbook pro m1

**Comment by dvoidus** [comment]
`xattr -cr /Applications/Alpaca\ Electron.app/`
fixed it for me

**Comment by brass458** [comment]
> `xattr -cr /Applications/Alpaca\ Electron.app/` fixed it for me

This worked for me - Apple M2 Pro 16" - Ventura 13.3.1
