### ISSUE TITLE
a great UI, but i feel it needs some more features

### ISSUE THREAD

**Issue by codingnow1** [ItsPi3141/alpaca-electron#36]
this UI is by far the best one i have used. but i feel like there can be some stuff to be added.

1. conversations: i think it would be really nice if there can be multiple conversations active at the same time like in chatgpt.
2.changing the AI's icon: its a really small thing but i think it would be really nice if you could change the little icon for the AI. maybe 
   even to upload your own. and thats it. hope you will consider adding these.

**Comment by chriswalt11** [comment]
You actually can change the icons rather easily on windows. Find your Alpaca Electron shortcut, and click "Open File Location". The path you're looking for should look something like: "C:\Users\USERNAME\AppData\Local\Programs\alpaca-electron\resources\app\src\img

From there, just put in a 64x64 .png file in the folder, and rename it as "user" or "alpaca" accordingly. This will replace the icons. Though, having the feature to hotswap icons within the program would be a neat feature too.

Having multiple conversations, along with the conversations being saved and persisting between sessions would be a great help. Also having the capability to add in extensions for internet searching would be nice too, but understandably not a priority at this time.

**Comment by ItsPi3141** [comment]
I'm working on trying to find the best way to save conversations and load them.

**Comment by codingnow1** [comment]
> You actually can change the icons rather easily on windows. Find your Alpaca Electron shortcut, and click "Open File Location". The path you're looking for should look something like: "C:\Users\USERNAME\AppData\Local\Programs\alpaca-electron\resources\app\src\img
> 
> From there, just put in a 64x64 .png file in the folder, and rename it as "user" or "alpaca" accordingly. This will replace the icons. Though, having the feature to hotswap icons within the program would be a neat feature too.
> 
> Having multiple conversations, along with the conversations being saved and persisting between sessions would be a great help. Also having the capability to add in extensions for internet searching would be nice too, but understandably not a priority at this time.
> 
> One other feature i'd like is to be able to remove previous messages individually, and even modify them. Occasionally I get bad responses that ends up "tainting" the memory so to speak, which requires me to end up clearing the chat and starting over. A mild frustration.

thanks!
