### ISSUE TITLE
API Endpoint

### ISSUE THREAD

**Issue by 0pilatos0** [ItsPi3141/alpaca-electron#44]
**Is your feature request related to a problem? Please describe.**

I'd like to request a feature to create an API endpoint to interact with the AI without using the interface. The problem is that currently, users are required to use the interface to interact with the AI, which may not be ideal for certain use cases, such as automating interactions with the AI or integrating it with other applications.

**Describe the solution you'd like**

I would like to have an API endpoint that allows users to programmatically interact with the AI. This would involve providing a set of input parameters and receiving the corresponding output from the AI in a structured format, such as JSON or XML. Ideally, the API endpoint would support various types of interactions with the AI, such as querying for information, training the AI, and controlling its behavior.

**Describe alternatives you've considered**

One alternative solution would be to provide a command-line interface (CLI) for interacting with the AI, as this would allow users to script interactions with the AI. However, a CLI may not be as flexible or powerful as an API endpoint, as it would require users to manually parse and format the input and output data. Another alternative solution would be to provide a library or SDK for interacting with the AI, but this may not be as widely accessible as an API endpoint.

**Additional context**

I believe that providing an API endpoint for the AI would greatly enhance its usability and integration capabilities. It would allow users to automate interactions with the AI, integrate it with other applications, and build custom interfaces on top of it. Additionally, it would make the AI more accessible to developers who are familiar with programming but may not be familiar with the AI's interface.

**Comment by ItsPi3141** [comment]
See https://github.com/ggerganov/llama.cpp

You can create a simple NodeJS app with express and nodepty to interact with llama.cpp cli.
