### ISSUE TITLE
模型去哪里下载呢？

### ISSUE THREAD

**Issue by yingjiezx123** [ItsPi3141/alpaca-electron#47]
![image](https://user-images.githubusercontent.com/105833757/231338324-f3f21377-4a0a-4646-b181-6b1ef54fb45a.png)
https://github.com/Pi3141/这个仓库里面没有了

**Comment by ItsPi3141** [comment]
???

**Comment by ranyong1997** [comment]
https://huggingface.co/Pi3141/alpaca-7b-native-enhanced/tree/main
