### ISSUE TITLE
Error:Cannot find module '../build/Release/pty.node'

### ISSUE THREAD

**Issue by vZzzv** [ItsPi3141/alpaca-electron#50]
App threw an error during load
Error: Cannot find module '../build/Release/pty.node'
Require stack:
- /Users/zzz/Downloads/alpaca-electron/node_modules/node-pty-prebuilt-multiarch/lib/prebuild-loader.js
- /Users/zzz/Downloads/alpaca-electron/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js
- /Users/zzz/Downloads/alpaca-electron/node_modules/node-pty-prebuilt-multiarch/lib/index.js
- /Users/zzz/Downloads/alpaca-electron/index.js
- /Users/zzz/Downloads/alpaca-electron/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/zzz/Downloads/alpaca-electron/node_modules/node-pty-prebuilt-multiarch/lib/prebuild-loader.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)

What kind of problem is that

**Comment by ItsPi3141** [comment]
What OS?

**Comment by vZzzv** [comment]
您发给我的信件已经收到。

**Comment by ItsPi3141** [comment]
I don't understand...

我不明白

Can you explain more?

你能解释更多吗？

**Comment by vZzzv** [comment]
in. mac os Monterey

I reported this error while running npm run start with vscode

![image](https://user-images.githubusercontent.com/31469501/231676862-9df0a92e-de6d-46fd-8da9-69bb3c4342e6.png)

When I get an error, I can run it, but it doesn't show up when I click on the file

![image](https://user-images.githubusercontent.com/31469501/231676969-3894883d-7c3d-4e8c-a0a9-61b4a58fac16.png)

**Comment by ItsPi3141** [comment]
>  in. mac os Monterey
> 
> I reported this error while running npm run start with vscode
> 
> ![image](https://user-images.githubusercontent.com/31469501/231676862-9df0a92e-de6d-46fd-8da9-69bb3c4342e6.png)

You need to run `npm run rebuild` before you start the app.

**Comment by vZzzv** [comment]
> > in. mac os Monterey
> > I reported this error while running npm run start with vscode
> > ![image](https://user-images.githubusercontent.com/31469501/231676862-9df0a92e-de6d-46fd-8da9-69bb3c4342e6.png)
> 
> You need to run before you start the app.`npm run rebuild`



zzz@192 alpaca-electron % npm run rebuild                          

> alpaca-electron@1.0.5 rebuild
> .\node_modules\.bin\electron-rebuild

sh: .node_modules.binelectron-rebuild: command not found

**Comment by vZzzv** [comment]
> > in. mac os Monterey
> > I reported this error while running npm run start with vscode
> > ![image](https://user-images.githubusercontent.com/31469501/231676862-9df0a92e-de6d-46fd-8da9-69bb3c4342e6.png)
> 
> You need to run before you start the app.`npm run rebuild`



zzz@192 alpaca-electron % npm run rebuild                          

> alpaca-electron@1.0.5 rebuild
> .\node_modules\.bin\electron-rebuild

sh: .node_modules.binelectron-rebuild: command not found

**Comment by ItsPi3141** [comment]
> sh: .node_modules.binelectron-rebuild: command not found

Oh sorry, it should be `npx electron-rebuild`

**Comment by vZzzv** [comment]
pm WARN deprecated electron-rebuild@3.2.9: Please use @electron/rebuild moving forward.  There is no API change, just a package name change

![image](https://user-images.githubusercontent.com/31469501/231923325-26b7f224-586c-46d2-ba57-e5bf532c59a0.png)


zzz@192 alpaca-electron % npm run rebuild

alpaca-electron@1.0.5 rebuild
.\node_modules.bin\electron-rebuild

sh: .node_modules.binelectron-rebuild: command not found

**Comment by vZzzv** [comment]
ok, it's ready to go, thank you
