### ISSUE TITLE
error and excess response: #### Instructions for Python code snippet

### ISSUE THREAD

**Issue by breakenknife** [ItsPi3141/alpaca-electron#52]
I use my alpaca-13B.bin and gpt4all-7B.bin to chat, but get some error and excess text at the end of response, eg:
![image](https://user-images.githubusercontent.com/12994391/231751332-0b8a3fa0-b907-4a73-9abe-da3cb8e53202.png)

is it a bug of alpaca-electron or some problem of my model?

**Comment by ItsPi3141** [comment]
That's just an Alpaca problem. Not related to Alpaca Electron.
