### ISSUE TITLE
Doesn't remember chat history.

### ISSUE THREAD

**Issue by SmallChief** [ItsPi3141/alpaca-electron#56]
See picture...

![image](https://user-images.githubusercontent.com/130750555/232011717-b6237a10-adb6-4944-84aa-21fbf77db095.png)

Alpaca electron v. 1.0.5
OS: WIN 10 Home Version 21H2

**Comment by ItsPi3141** [comment]
It does. Ask it to remember a number and then ask if to recall the number afterwards.

**Comment by SmallChief** [comment]
As suggested:

![image](https://user-images.githubusercontent.com/130750555/232110998-f055633b-7aae-485c-9f0b-404793b970d6.png)

Does not seem to work with numbers either on my end. =/

**Comment by ItsPi3141** [comment]
> Remember the number 7728 for me

> What number did I ask you to remember?
