### ISSUE TITLE
I found that the published exe had problems with Windows

### ISSUE THREAD

**Issue by vZzzv** [ItsPi3141/alpaca-electron#57]
Here is a model in Chinese
https://huggingface.co/Mabbs/chinese-Alpaca-lora-7b-ggml/tree/main

This Chinese model can be used normally on mac os
![image](https://user-images.githubusercontent.com/31469501/232037957-d03938cf-3a79-472e-81ed-e2451f10cb05.png)

The same model doesn't work well with win11, 22H2,
![image](https://user-images.githubusercontent.com/31469501/232038350-e0530c8e-fdd5-45cb-b80e-9843058afe3d.png)

What kind of problem is that

**Comment by vZzzv** [comment]
Alpaca Electron  1.0.5

**Comment by ItsPi3141** [comment]
It might just be the seed. As far as I know, they're the same.
