### ISSUE TITLE
display error after running docker compose in window.

### ISSUE THREAD

**Issue by Asmedeus998** [ItsPi3141/alpaca-electron#59]
**Describe the bug**
display error after running running following command `docker compose up -d` or `docker compose up`

here the error message:

**To Reproduce**
1. Go to `docker compose up -d` or `docker compose up`
2. See error:

`time="2023-04-15T16:27:20+08:00" level=warning msg="The \"DISPLAY\" variable is not set. Defaulting to a blank string."`

**Expected behavior**
successfully docker to run without any error 

**Desktop (please complete the following information):**
 - OS: window 10

**Comment by ItsPi3141** [comment]
On windows, you need to set the port of your X11 display server. Try running `export DISPLAY=:420` (replace 420 with whatever port you have it set to). And then run `docker compose up` again.

**Comment by TheTerrasque** [comment]
I haven't tried with this program, but I've had success with this setup on other docker based UI's under windows:

    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=/mnt/wslg/PulseServer
    volumes:
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
      - /run/desktop/mnt/host/wslg:/mnt/wslg
