### ISSUE TITLE
Support GPU as an option

### ISSUE THREAD

**Issue by fusir** [ItsPi3141/alpaca-electron#61]
Yes, running on only CPU is really cool especially for making these things accessible to more people.  But it's a good interface and if you have a graphics card you might as well use it.

Especially because some of us have really weird setups with budget CPUs and legitimate graphics cards.  Maybe I'm wrong to have a An RTX 3060 and a no AVX.

**Comment by ItsPi3141** [comment]
Then you should use oobabooga's text generation webui. This project never will support GPU.
