### ISSUE TITLE
arm64 1.0.5 not work on m1 air

### ISSUE THREAD

**Issue by kpk-i710** [ItsPi3141/alpaca-electron#62]
The "Alpaca Electron" application is corrupted and cannot be opened. Do you want to place the application in the Trash?

**Comment by Alex-idk** [comment]
I had the same issue, I ended up just building from source. [Here](http://alexidk.dev/cdn/Alpaca-Electron.zip) is a build with the latest commit.

**Comment by kpk-i710** [comment]
> I had the same issue, I ended up just building from source. [Here](https://alexidk.dev/cdn/Alpaca-Electron.zip) is a build with the latest commit.
Downloaded from your link, same error.

**Comment by kpk-i710** [comment]
> I had the same issue, I ended up just building from source. [Here](https://alexidk.dev/cdn/Alpaca-Electron.zip) is a build with the latest commit.



> 

Downloaded from your link, same error.

**Comment by MahdeenSky** [comment]
I fixed it by running this command `xattr -cr Alpaca\ Electron.app`

**Comment by kpk-i710** [comment]
> I fixed it by running this command `xattr -cr Alpaca\ Electron.app`

yes it works
