### ISSUE TITLE
Privacy issue with the current main branch! All prompts are sent to the internet (Duck Duck Go)

### ISSUE THREAD

**Issue by oderwat** [ItsPi3141/alpaca-electron#69]
This is here to want people that main is currently in a state that all your prompts are sent, do Duck Duck Go.

**Comment by ItsPi3141** [comment]
Just fixed, created a new [duckduckgo-search](https://github.com/ItsPi3141/alpaca-electron/tree/duckduckgo-search) branch. Main no longer sends prompt to duckduckgo.
