### ISSUE TITLE
Allow more cpu cores to be used

### ISSUE THREAD

**Issue by Jcwscience** [ItsPi3141/alpaca-electron#71]
Right now the software seems to be limited to 8 cores, however my computer has 12 and many other computers have even more. Would it be possible to change the max core count as a setting?

**Comment by ItsPi3141** [comment]
Its not limited to 8. Its limited to the maximum power of 2 under your CPU thread count. E.g. a 20thread CPU will use 16. This is to improve performance. Setting the number of threads to something other than a power of 2 causes performance to degrade. E.g. 8 threads will perform better than 12 threads.

**Comment by ItsPi3141** [comment]
> id rather have it leave some room for my other stuff too, its kinda greedy and it hogs my cpu if i have other stuff running, and im never going to just, not do other stuff at the same time, i wanna multi task and stuff (i have a ryzen so, it feels bad, this is the first time my pc CRAWLED)
> 
> like it should only use 90% of my cpu max, but if my cpu usage is already maxed out at 100%, it should lower itself to 90% again until i have more room for it

I won't make the CPU usage dynamic. That's for llama.cpp to do. You're running an LLM locally, don't expect your computer to be fast while it's running.
