### ISSUE TITLE
Provide source code to recompile bin/chat for some platforms

### ISSUE THREAD

**Issue by penghe2021** [ItsPi3141/alpaca-electron#72]
It's not a feature request actually, nor a bug, so I will just use this template since it is more related.

**Is your feature request related to a problem? Please describe.**
For those who use Ubuntu20.04 and are facing this issue
`XXXXXXXXXXX: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34 not found. `
`/lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32 not found`
it maybe because the library bin/chat needs to be recompiled in you own system, I tried to use the one I built from the latest alpaca.cpp, but some keywords are different 

**Describe the solution you'd like**
Can we have the source code so we can recompile it?

BTW: nice work

**Comment by penghe2021** [comment]
Please correct me if I am wrong, I am not very familiar with llama.cpp

The detailed error I got from the terminal is
`Alpaca Electron-linux-x64/resources/app/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32' not found (required by xxx/bin/chat)` 

Most likely this library `xxx/bin/chat` is compiled using Ubuntu 22.04. That's why I assume I need to recompile it (I am using 20.04).

After I ran the make under llava home folder, I can use my ggml model successfully, but I cannot find the `chat` library. I will be very thankful if you can tell me how to get this library: `bin/chat`.

**Comment by ItsPi3141** [comment]
> After I ran the make under llava home folder, I can use my ggml model successfully, but I cannot find the `chat` library. I will be very thankful if you can tell me how to get this library: `bin/chat`.

Oh just rename main to chat. I renamed it when transitioning from alpaca.cpp to llama.cpp. I'll rename it back at some point later on.

**Comment by penghe2021** [comment]
It works, thanks for the help!

**Comment by penghe2021** [comment]
Sure, this is the chat file: https://drive.google.com/file/d/1xgAfSKADKKv8nq7EW4JZ85TJWhO7ianR/view?usp=share_link
My system version:
`Ubuntu 20.04.6 LTS
`
