### ISSUE TITLE
[BUG] Right now it only works for the model with one bin file, does it work with models of splited bin files?  

### ISSUE THREAD

**Issue by Keith-Zh** [ItsPi3141/alpaca-electron#77]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 1.0.5]

**Additional context**

**Comment by ItsPi3141** [comment]
No, it doesnt work with split bin files. This is only for llama models, so what I might do is create my own version of llama ggml model that is a single file instead of split.
