### ISSUE TITLE
Stable Vicuna 13B GGML (Q5_1) does not compute [BUG] 

### ISSUE THREAD

**Issue by erkkimon** [ItsPi3141/alpaca-electron#78]
**Describe the bug**

Alpaca 7B Native Enhanced (Q4_1) works fine in my Alpaca Electron. However, I tried to use the latest Stable Vicuna 13B GGML (Q5_1) which doesn't seem to work. It loads fine but gives me no answers, and keeps running the spinner forever instead. If I understand it right, it theoretically should work and there should be nothing that technically would make it incompatible with Alpaca Electron. Well it doesn't seem to work anwyay. 

**To Reproduce**
1. Install Alpaca Electron v1.0.5.
2. Download Stable Vicuna 13B GPTQ (Q5_1) [here](https://huggingface.co/TheBloke/stable-vicuna-13B-GPTQ).
3. Load the Q5_1 using Alpaca Electron.
4. Say "hello".
5. Nothing happens.

**Expected behavior**
The chat should say hello or something.

**Screenshots**
<img width="1201" alt="Screenshot 2023-05-01 at 14 40 38" src="https://user-images.githubusercontent.com/2260825/235446940-54ac7455-3f2b-4136-af56-9332b4329500.png">

**Desktop (please complete the following information):**
I'm running Mac OS X Ventura 13.3.1 @ Intel Iris Plus Graphics 1536 MB && 2,3 Ghz Quad-Core Intel Core i7 Processor && 16 GB of memory. My Alpaca Electron is v1.0.5.

**Comment by erkkimon** [comment]
I realized that the problem might be 5-bit GGML. Anyway, I tried also 4-bit Stable Vicuna 13B (Q4_2) and the result is the same. What could cause it?

**Comment by ItsPi3141** [comment]
It should be ggml, not gptq.

**Comment by erkkimon** [comment]
Now after some more testing, I found out that stable-vicuna-13B.ggml.q4_0.bin seems to work on my system.
