### ISSUE TITLE
add support any russian model [ENHANCEMENT]

### ISSUE THREAD

**Issue by asidsx** [ItsPi3141/alpaca-electron#82]
most russian models were made with transformers or PyTorch like https://huggingface.co/ai-forever/rugpt3large_based_on_gpt2/tree/main
Can you add support to this format or create converter?

**Comment by Steelman14aUA** [comment]
bhgg ruzzian

**Comment by ItsPi3141** [comment]
The model you linked isn't supported by llama.cpp. so unfortunately, no, I cannot add support for it.
