### ISSUE TITLE
[QUESTION][ENHANCEMENT]Portability - multi device mode

### ISSUE THREAD

**Issue by pietru2004** [ItsPi3141/alpaca-electron#83]
**Is your feature request related to a problem? Please describe.**
Would it be possible to run app in server mode? 
This could allow app to be used from phones or remote pcs.

Server mode could have own directory/setting for selecting model to load.

**Comment by ItsPi3141** [comment]
I probably won't do that. You should look at Dalai if you're interested in that. https://github.com/cocktailpeanut/dalai
