### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by DEGENMUTANT** [ItsPi3141/alpaca-electron#86]
Another great plan going forward with this Awesome AiBot would be to add internet connections, so prompts will be in real-time. ie example ==
What's the regional price of gas in "User inputs his\her Your country or State or Region" ?
Alpaca-Electron: Generate Accurate Response to the best of its capabilities

**Comment by ItsPi3141** [comment]
Its already been added. The new version just hasn't been released yet because it's not complete.
