### ISSUE TITLE
Alpaca-Electron-mac-arm64-v1.0.5 app is "damaged".

### ISSUE THREAD

**Issue by dr2chase** [ItsPi3141/alpaca-electron#90]
**Describe the bug**
MacOS reports: “Alpaca Electron” is damaged and can’t be opened. You should move it to the Trash.

**To Reproduce**
1. Download https://github.com/ItsPi3141/alpaca-electron/releases/download/v1.0.5/Alpaca-Electron-mac-arm64-v1.0.5.dmg
2. Click on the downloaded dmg
3. Move Alpaca Electron to Applications
4. Click on Alpaca Electron in Applications
5. See error message.
6. Try control-click instead.
7. Still see error message.

**Expected behavior**
Alpaca Electron at least opens.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS arm64
 - Version Ventura 13.4 (22F66)

**Additional context**
I've been trying to find some way to run an LLM locally on a beefy laptop, and thus far nothing anyone has recommended has worked, so this lengthens the amusing tale of fail.

**Comment by broderix** [comment]
> **Describe the bug** MacOS reports: “Alpaca Electron” is damaged and can’t be opened. You should move it to the Trash.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Download https://github.com/ItsPi3141/alpaca-electron/releases/download/v1.0.5/Alpaca-Electron-mac-arm64-v1.0.5.dmg
> 2. Click on the downloaded dmg
> 3. Move Alpaca Electron to Applications
> 4. Click on Alpaca Electron in Applications
> 5. See error message.
> 6. Try control-click instead.
> 7. Still see error message.
> 
> **Expected behavior** Alpaca Electron at least opens.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: MacOS arm64
> * Version Ventura 13.4 (22F66)
> 
> **Additional context** I've been trying to find some way to run an LLM locally on a beefy laptop, and thus far nothing anyone has recommended has worked, so this lengthens the amusing tale of fail.

Try this in terminal
`xattr -cr /Applications/Alpaca\ Electron.app/`

**Comment by dr2chase** [comment]
Success! (it starts and whines at me about wanting an Alpaca model).  Not sure if this counts as closable or not.

**Comment by ha1tch** [comment]
FWIW I'm experiencing exactly the same

**Comment by ItsPi3141** [comment]
Please look at the Troubleshooting section in the readme file. 

https://github.com/ItsPi3141/alpaca-electron#macos
